### ISSUE TITLE
Volunteer Report: HourRedemption: AccountID/PrizeID

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#191]
Can we get the following derived on the HourRedemption raw report?

Account ID: Volunteer Name (Preferred Name)
Prize ID: Prize Name

Can we also add the Volunteer Email address? 

We need this for the Volunteer Party raffle. If this can be done in the next few days, great. If not, let me know and I work on a work around. 

![screen shot 2018-07-23 at 9 40 28 pm](https://user-images.githubusercontent.com/37823973/43113727-206a172e-8ec1-11e8-806d-5801da660922.png)

**Comment by AricStewart** [comment]
This is harder because we dont (yet) store Names and Emails in our databases they remain in Neon.

So this derived table can be made but it will take quite a while due to all the Neon queries.  In the next generation of the portal this will become trivial. 

I will try to get something for you in the next couple of days but expect it to be a temporary fix until we get farther in the migration off Neon.

**Comment by lmhern1** [comment]
OK, sounds good. The individual department reports include the name and email address, so it looked like it was already being done in Signin. 
<img width="1312" alt="screen shot 2018-07-25 at 9 34 50 am" src="https://user-images.githubusercontent.com/37823973/43207662-2e0fab9a-8fee-11e8-8e2b-ba044c76fa7d.png">

**Comment by AricStewart** [comment]
Yeah, I am going to try to get something put together for you today and see if Thomas can get it in by Friday for you.  It is just going to be a bit more hacky than I would like. :) and may take a bit longer to generate.
