### ISSUE TITLE
Full CSS support

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#241]
We need to ensure that our current codebase fully supports CSS, and identify any gaps in order to be able to re-skin or update the UI as we start our UI/UX review.  Tag or comment in any related known issues here.(?)

**Comment by AricStewart** [comment]
We mostly use the w3school css sheet. There is a little bit of custom skin-able functionality that I added in around icons and colors but it has not been a priority. 

Or codebase does full support CSS and should be responsive to changes there.

**Comment by AricStewart** [comment]
Thinking more about this we could do something cool using SASS or such to have the css be even more dynamically scriptable.  Then would could write the project itself pretty css agnostic, even down the the framework, and then have SASS files that compile into CSS.

But that would then require as CSS compilation process before the project would be viewable.

**Comment by mshappe** [comment]
As someone who uses SASS/SCSS under Rails all the time, I recommend it highly, actually. The compilation step can be automated even for development purposes (I assume there are tools to do this for PHP; there certainly are for other environments). Compared to straight CSS, any of the CSS+Macro languages (SASS, SCSS, LESS) are a vast improvement.

**Comment by AricStewart** [comment]
oooh someone who has experience there.  FYI I am not a web developer at all. I am a back end guy. So all the web stuff I have done for this project is out of my generally knowledge sphere. 

Do you think we should check in the compiled CSS as well as the SCSS? Then when someone changes the SCSS we obligate them to check in the compiled CSS as well?

Do we require SCSS compiler to be installed on the target system and compile on install time (like the vendor stuff for php)?

I like SCSS or such because the would like us do 
`@import "../../../sitesupport/w3";
@import "../../../sitesupport/event";

.sectionbar {
    @extend .event-color-primary;
    @extend .w3-xlarge;
    @extend .w3-center;
}`

Effectively extending a class to use whatever framework we are using (w3 at this point). Then if we choose to jump to bootstrap or something we do not have to change as much of the PHP code itself.

LESS (which would NOT have to be re-compiled) only allows extending from classes IN the file, not from includes. 

Thoughts?

**Comment by mshappe** [comment]
We should not check in compiled CSS. Rather, when we deploy to
production-like environments, part of deployment should include that
compilation--for example, in the Dockerverse, the production Dockerfile
would do it and make it part of the image.

In development, I need to do some research into how this is done with PHP.
Rails has magic that basically interprets these things on the fly in dev,
but again allows them to be compiled for prod-like environments. Rails
calls this the Asset Pipeline, and like most magic, to be honest, it's a
mixed bag of "great" when it works and "what the hell just happened?!" when
it doesn't :-)

That said, I have to believe that, just as PHP has `composer` as an analog
to `bundler`, there is some analog to at least magically compiling
SASS/SCSS on the fly for development purposes.

**Comment by AricStewart** [comment]
This the sort of things you are describing?

https://stephencoakley.com/2014/05/22/using-sass-in-php-projects

Specifically maybe using leafo/scssphp in our composer file

then maybe using scssphp_server to on demand compile the css?  That would be nice.

You researching or shall I?

**Comment by mshappe** [comment]
After a quick skim, I'd say yes, that's more or less what I had in mind.
You can research if you like -- I'm juggling board things today.

**Comment by mshappe** [comment]
I feel like we can close this now? Thoughts?

**Comment by AricStewart** [comment]
Agreed
