### ISSUE TITLE
Concom List: Executive offices can only be removed

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#293]
There does not appear to be any way to edit or add executive offices (president, secretary, etc), only to remove them.

**Comment by AricStewart** [comment]
Ok, This has been explicitly blocked in code since the original Thomas version in Feb 2017.  Is there a reason? I would like Thomas' input or at least a decision as to if there was a reason behind that code?  It is trivial to remove the check and allow additions to "Corporate Staff" and "Committees". Which are the 2 divisions where adding staff is explicitly blocked in code.

**Comment by mshappe** [comment]
@tskeeley

**Comment by tskeeley** [comment]
I'm okay with removing the block.

However, I would like it kept to only-admins can update "non-department" staff/committees.  (eg: corp staff, CFO/finance, SRD, etc)  BUT, once someone is set as a "head" level in whatever it is, they can have head rights to it, specifically the SRD board members need to be able to add/remove people.  And, in my opinion, the Board Liaison to committees should be able to add/remove instead of having to wait on an admin.  The one's I'm worries around are corp staff specifically as there is a legal repercussion for those changing, and I don't want someone that isn't an admin to have to worry about that.

Oh, and, to be honest, the REAL reason it was blocked was because I was filtering out the non-departments in the original php version.  That's SO not applicable now. :)

Thank you for checking on it though!!

**Comment by AricStewart** [comment]
Should now be fixed.
