### ISSUE TITLE
Enter Hours Page: Date/Time that the Shift Ended Field: 15 Minute Increments

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Signin#97]
Enhancement: CHANGE Limit date/time to 15 minute increments (when logging hours). In practice, we round up to the nearest 15 minutes when logging volunteer hours.

**Comment by AricStewart** [comment]
It is recorded this way in the database. It is just not displayed this way when you enter it.

**Comment by AricStewart** [comment]
Question:  Round to nearest up or down? Or always up?

If I work for 1-7 minutes do I get credit of 0 or 15.

**Comment by tskeeley** [comment]
the goal on this is to make it so that if someone is entering time, they don't have the option of entering anything but :00 :15 :30 or :45 for the minutes of the end time field.

Rounding shouldn't come into play here because the issue is, users entering info can be...  distracted, and we want to make it as simple as possible.  I used the "time" field because I was lazy.  I should have coded for :00 :15 :30 :45 when I made the form.  (and if you need me too, I'll fix it)

**Comment by AricStewart** [comment]
Accepted
